// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acwmndigzvycfgwzngmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjd21uZGlnenZ5Y2Znd3puZ21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTExOTgsImV4cCI6MjA2OTM2NzE5OH0.eX69k-wiZ05PgR38NEmghGt-u4roPqEVTVtnjRaTDUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});